//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_ServiceTests.OrderServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceReference.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/addOrder", ReplyAction="http://tempuri.org/IOrderService/addOrderResponse")]
        void addOrder(WCF_Service.DataTransferObjects.OrderDTO newOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/addOrder", ReplyAction="http://tempuri.org/IOrderService/addOrderResponse")]
        System.Threading.Tasks.Task addOrderAsync(WCF_Service.DataTransferObjects.OrderDTO newOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/getOrders", ReplyAction="http://tempuri.org/IOrderService/getOrdersResponse")]
        System.Collections.Generic.List<WCF_Service.DataTransferObjects.OrderDTO> getOrders(int customerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/getOrders", ReplyAction="http://tempuri.org/IOrderService/getOrdersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WCF_Service.DataTransferObjects.OrderDTO>> getOrdersAsync(int customerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : WCF_ServiceTests.OrderServiceReference.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<WCF_ServiceTests.OrderServiceReference.IOrderService>, WCF_ServiceTests.OrderServiceReference.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void addOrder(WCF_Service.DataTransferObjects.OrderDTO newOrder) {
            base.Channel.addOrder(newOrder);
        }
        
        public System.Threading.Tasks.Task addOrderAsync(WCF_Service.DataTransferObjects.OrderDTO newOrder) {
            return base.Channel.addOrderAsync(newOrder);
        }
        
        public System.Collections.Generic.List<WCF_Service.DataTransferObjects.OrderDTO> getOrders(int customerID) {
            return base.Channel.getOrders(customerID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WCF_Service.DataTransferObjects.OrderDTO>> getOrdersAsync(int customerID) {
            return base.Channel.getOrdersAsync(customerID);
        }
    }
}
